project                  = "project_id"
region                   = "us-central1"
first_network_name       = "test-network1-076-red"
second_network_name      = "test-network2-076-red"
network_peering_one_name = "peering-076-red"
