project       = "project_id"
region        = "us-central-1"
machine_type  = "n2d-standard-2"
template_name = "confidential-386-green"
network       = "default"
image         = "projects/confidential-vm-images/global/images/ubuntu-pro-fips-2004-focal-v20220829"
nic           = "GVNIC"
