project       = "project_id"
region        = "us-central1"
zone          = "us-central1-a"
instance_name = "no-project-wide-ssh-keys-for-instances-035-green"
machine_type  = "f1-micro"
network       = "default"
