project       = "project_id"
region        = "us-central1"
zone          = "us-central1-a"
instance_name = "not-default-service-171-green"
network       = "default"
sa_id         = "service-account-171-green"
sa_name       = "Service Account"
