name: "Installing cloud-custodian"
description: "Installing cloud-custodian"
runs:
  using: "composite"
  steps: 
  - run: |
      command -v git >/dev/null || ( apt-get update -y && apt-get install git -y )
      DEFAULT_CORE_BRANCH=main
      CORE_BRANCH=$GITHUB_BASE_REF
      echo "CORE_BRANCH = $CORE_BRANCH"
      CORE_BRANCH=${CORE_BRANCH:-$GITHUB_REF_NAME}
      echo "CORE_BRANCH = $CORE_BRANCH"
      if [[ $CORE_BRANCH != "develop" && $CORE_BRANCH != "main" ]]; then CORE_BRANCH=$DEFAULT_CORE_BRANCH; fi
      echo "Using $CORE_BRANCH in cloud-custodian"
      echo "Core branch = $CORE_BRANCH"
      git clone https://github.com/cloud-custodian/cloud-custodian.git --branch $CORE_BRANCH --depth 1
      mkdir gcp-custodian-policies && cp -r policies tests gcp-custodian-policies
      cp -r gcp-custodian-policies cloud-custodian
      cp .github/workflows/scripts/policy_as_test.py cloud-custodian/.
      cp .github/workflows/scripts/gcp_common.py cloud-custodian/tools/c7n_gcp/tests/.
      cp .github/workflows/scripts/green_policy_test.py cloud-custodian/.
    shell: bash