# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-gcp-134-kubernetes_cluster_istioconfig_not_enabled
    comment: '030023072000'
    description: |
      Kubernetes cluster istioConfig is not Enabled
    resource: gcp.gke-cluster-beta-api
    filters:
      - type: value
        key: addonsConfig.istioConfig.disabled
        op: eq
        value: true
