project       = "project_id"
region        = "us-central-1"
machine_type  = "f1-micro"
template_name = "template-231-green"
network       = "default"
check_name    = "health-check-231-green"
group_name    = "group-231-green"
