project       = "project_id"
region        = "us-central1"
zone          = "us-central1-a"
instance_name = "confidential-computing-enabled-197-green"
machine_type  = "n2d-standard-2"
network       = "default"