# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-gcp-018-log_metric_for_audit_configurations
    comment: '030019011000'
    description: |
      The project does not have Log metric filter and alerts for Audit Configuration Changes
    resource: gcp.project
    filters:
      - not:
          - type: logging-metrics-filter
            key: filter
            op: eq
            value: "protoPayload.methodName=\"SetIamPolicy\" AND protoPayload.serviceData.policyDelta.auditConfigDeltas:*"
