# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-gcp-260-bigtable_table_configured_without_privileged_service_accounts
    description: |
      Cloud Bigtable table configured with privileged service account
    resource: gcp.bigtable-instance-table
    filters:
      - type: gcp-iam-policy-filter
        key: role
        value: ["roles/editor", "roles/owner"]
        op: in
      - type: gcp-iam-policy-filter
        key: members[]
        value: '.*serviceAccount.*'
        op: regex
