# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-gcp-231-instance_configured_with_autohealing
    description: |
      Google Cloud Managed Instance Groups (MIGs) are configured without Autohealing feature.
    resource: gcp.instance-group-managers
    filters:
      - type: value
        key: autoHealingPolicies
        value: absent
    comment: '0120032000'
