project     = "project_id"
region      = "us-central1"
said        = "service-account-260-green"
saname      = "Service Account 260"
tname       = "table-260-green"
iname       = "instance-260-green"
clusterzone = "us-central1-b"
