project    = "project_id"
region     = "us-central1"
sa         = "service-account-292-red"
spanner-i  = "spanner-instance-292-red"
spanner-db = "spanner-db-292-red"
spanner-bu = "spanner-bu-292-red"
rule       = "ecc-gcp-292-spanner_backup_without_privileged_service_account"