# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-gcp-254-app_engine_application_custom_domain_ssl_certificate_expiration
    description: |
      Cloud App Engine application custom domain SSL certificate expires in less than 30 days
    resource: gcp.app-engine-certificate
    filters:
      - type: value
        key: expireTime
        op: lt
        value_type: expiration
        value: 30