# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-gcp-347-spanner-instance-with-multi-region-configuration
    description: |
      Cloud Spanner Instance is deployed without multi-region configuration
    resource: gcp.spanner-instance
    filters:
      - type: value
        key: config
        op: regex
        value: 'projects/.*/instanceConfigs/regional.*'