# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-gcp-400-password_history_flag_configured_for_mysql
    comment: '030023062000'
    description: |
      The 'password_history' database flags for Cloud SQL MySQL instance are not configured
    resource: gcp.sql-instance
    filters:
      - type: value
        key: databaseVersion
        value: "MYSQL"
        op: contains
      - type: value
        key: settings.databaseFlags[].name.password_history
        value: absent
