# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-gcp-246-functions_configured_with_vpc_connector
    description: |
      Cloud Functions function is not configured with a VPC connector
    resource: gcp.function
    filters:
      - type: value
        key: vpcConnector
        value: absent