# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-gcp-245-cloud_functions_configured_without_default_service_account
    description: |
      Cloud Functions function is configured with default service account
    resource: gcp.function
    filters:
      - type: value
        key: serviceAccountEmail
        op: regex
        value: '^.*@appspot.gserviceaccount.com'