# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-gcp-409-os-patch-deployment-configured-with-recurring-schedule
    comment: '030020032000'
    description: |
      OS Patch Deployment is not configured with a recurring schedule
    resource: gcp.patch-deployment
    filters:
      - type: value
        key: recurringSchedule
        value: absent
