# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-gcp-130-kubernetes_engine_clusters_not_configured_with_network_traffic_egress_metering
    description: |
      Kubernetes Engine Clusters are not configured with network traffic egress metering
    resource: gcp.gke-cluster
    filters:
      - type: value
        key: resourceUsageExportConfig.bigqueryDestination.datasetId
        value: present
      - type: value
        key: resourceUsageExportConfig.enableNetworkEgressMetering
        op: ne
        value: true