# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-gcp-132-kubernetes_cluster_application-layer_secrets_not_encrypted
    description: |
      Kubernetes cluster Application-layer Secrets are not encrypted
    resource: gcp.gke-cluster
    filters:
      - type: value
        key: databaseEncryption.state
        op: ne
        value: "ENCRYPTED"