name: test-custodian-policies
on:
  workflow_dispatch:
  push:
  pull_request_review:
    types: 
      - submitted
jobs:
  test_policy_flights:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compliance: ['red', 'green']
    container:
      image: python:3.8
      env:
        COMPLIANCE: ${{ matrix.compliance }}
    if: github.event_name == 'push' || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
    steps: 
      - uses: actions/checkout@v4
      - name: Checkout ecc-actions
        run: git clone -b support_fork_for_flight_tests "https://git:$PROJECT_TOKEN@git.epam.com/epmc-sec/cloudlab/cloud_custodian/ecc-actions.git" ecc-actions
        env:
          PROJECT_TOKEN: ${{ secrets.ECC_CHANGELOG_ACTION }}
      - uses: ./ecc-actions/flight-test-dependencies
        env:
          PROJECT_TOKEN: ${{ secrets.CLOUDCUSTODIAN_CORE }}
      - uses: ./ecc-actions/flight-test-action
        env:
          COMPLIANCE: ${{ matrix.compliance }}

  build:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [test_policy_flights]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout ecc-actions
        run: git clone -b main "https://git:$PROJECT_TOKEN@git.epam.com/epmc-sec/cloudlab/cloud_custodian/ecc-actions.git" ecc-actions
        env:
          PROJECT_TOKEN: ${{ secrets.ECC_CHANGELOG_ACTION }}

      - name: Create wiki
        uses: ./ecc-actions/generate-list-of-rules

      - name: Release action
        uses: ./ecc-actions/release-rulepack-action
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
